import 'dart:ui';

import 'package:flutter_app_paul_test/custom_flutter_widgets/card_widget.dart';

const MAIN_COLOR = const Color(0xAFD97A00);
const Map<String, String> Car_Types = const {
  "Class M": "Class M: Motorcycles",
  "Class I": "Class I: Saloon cars and tricycles",
  "Class II":
      "Class II: Sports Utility Vehicles (SUVs), minibuses, and pick-up trucks",
  "Class IIA": "Class IIA: Commercial danfo minibuses",
  "Class III": "Class III: Light trucks and 2-axle buses"
};
const String Authorization =
    'Bearer sk_test_fd4de30832bc5641ba1ef6467f93cdc3e6d68b9b';

List<CardWidget> testcards = [
  new CardWidget(
      name: 'TEST CARD 1 - No validation',
      cardnum: '408 408 408 408 408 1',
      expiry: '01/23',
      cvv: '408',
      pathimage: 'assets/9PSBCard_front.PNG'),
  new CardWidget(
      name: 'PIN(1234)+OTP(123456)',
      cardnum: '5060 6666 6666 6666 666',
      expiry: '04/21',
      cvv: '123',
      pathimage: 'assets/9PSBCard_front.PNG'),
  new CardWidget(
      name: 'TESTCARD3 - PIN only(1111)',
      cardnum: '5078 5078 5078 5078 12',
      expiry: '01/23',
      cvv: '081',
      pathimage: 'assets/9PSBCard_front.PNG'),
  new CardWidget(
      name: 'PIN(0000)+PHONE+OTP(123456)',
      cardnum: '5078 5078 5078 5078 04',
      expiry: '01/23',
      cvv: '884',
      pathimage: 'assets/9PSBCard_front.PNG'),
  new CardWidget(
      name: 'TEST CARD 5 - Bank authorization Simulation',
      cardnum: '408 408 0000000 409',
      expiry: '01/23',
      cvv: '000',
      pathimage: 'assets/9PSBCard_front.PNG')
];

Map Abreviation_Plate = {
  "RSH": ["Abuja", "Karshi Area Council"],
  "RBC": ["Abuja", "Rubuchi Admin council"],
  "KWL": ["Abuja", "Kwali Area Council"],
  "KUJ": ["Abuja", "Kuje Area Council"],
  "ABC": ["Abuja", "Abuja municipal Council"],
  "ABJ": ["Abuja", "Abaji Area Council"],
  "BWR": ["Abuja", "Bwari Area Council"],
  "ADK": ["Ekiti", "Ado Ekiti"],
  "KER": ["Ekiti", "Ikere Ekiti"],
  "AMK": ["Ekiti", "Aramoko Ekiti"],
  "EFY": ["Ekiti", "Efon Alaye"],
  "KLE": ["Ekiti", "Ikole Ekiti"],
  "TUN": ["Ekiti", "Moba LG (Otun)"],
  "EMR": ["Ekiti", "Emure Ekiti"],
  "MUE": ["Ekiti", "Omuo Ekiti"],
  "AKR": ["Ondo", "Akure south (Akure)"],
  "JTA": ["Ondo", "Akure North (Ita Ogbolu)"],
  "FGB": ["Ondo", "Ifedore (Igbara-Oke)"],
  "WWW": ["Ondo", "Owo (Owo)"],
  "LEL": ["Ondo", "Ile Oluji (Ile Oluji)"],
  "NND": ["Ondo", "Ondo West (Ondo)"],
  "BDR": ["Ondo", "Ondo East (Bolorunduro)"],
  "WEN": ["Ondo", "Idanre (Owena)"],
  "SUA": ["Ondo", "Akoko South East (Isua)"],
  "REE": ["Ondo", "Odigbo  (Ore)"],
  "GBA": ["Ondo", "Igbokoda ( Igbokoda)"],
  "KTP": ["Ondo", "Okitipupa"],
  "ANG": ["Ondo", "Akoko Northwest (oke Agbe)"],
  "FFN": ["Ondo", "Ose LG (Ifon)"],
  "KAA": ["Ondo", "Iwaro Oka or Ikare"],
  "LES": ["Osun", "Ilesa"],
  "KRE": ["Osun", "Ikire"],
  "SGB": ["Osun", "Ogbogbo"],
  "GBN": ["Osun", "Gbongon"],
  "FNN": ["Osun", "Ifon Osun"],
  "EDE": ["Osun", "EDE"],
  "BDJ": ["Oyo", "Bodija Ibadan"],
  "AME": ["Oyo", "Arowomole (Ogbomosho)"],
  "LUY": ["Oyo", "Oluyole (Ibadan)"],
  "MAP": ["Oyo", "Mapo (Ibadan)"],
  "SEY": ["Oyo", "Iseyin"],
  "GBR": ["Oyo", "Igbo Ora"],
  "NRK": ["Oyo", "Onireke (Ibadan)"],
  "YYY": ["Oyo", "(Oyo east LG) Headquarter in Kosobo"],
  "FMT": ["Oyo", "(Atiba LG) Headquarters in Offa Meta"],
  "JND": ["Oyo", "(Oyo west LG) Headquarters in Ojongbodu"],
  "JBL": ["Oyo", "(Afijio LG) Headquarters in Jobele and its JBL"],
  "FST": ["Lagos", "Festac"],
  "SMK": ["Lagos", "Somolu"],
  "JJJ": ["Lagos", "Ojo"],
  "KJA": ["Lagos", "Ikeja"],
  "AAA": ["Lagos", "Lagos Island LG"],
  "FKJ": ["Lagos", "Ifako Ijaiye"],
  "AKD": ["Lagos", "Ibeju Lekki"],
  "LND": ["Lagos", "Lagos Mainland"],
  "LSR": ["Lagos", "Surulere"],
  "LSD": ["Lagos", "Oshodi Isolo"],
  "KSF": ["Lagos", "Kosofe"],
  "AGL": ["Lagos", "Ajeromi Ifelodun"],
  "APP": ["Lagos", "Apapa"],
  "KTU": ["Lagos", "Alimosho"],
  "BDG": ["Lagos", "Badagry"],
  "EKY": ["Lagos", "Eti-Osa LG"],
  "KRDI": ["Lagos", "korodu"],
  "EPE": ["Lagos", "Epe"],
  "MUS": ["Lagos", "Mushin"],
  "GGE": ["Lagos", "Agege"],
  "BKR": ["Katsina", "Bakori"],
  "BAT": ["Katsina", "Batagarawa"],
  "BTR": ["Katsina", "Batsari"],
  "BRE": ["Katsina", "Baure"],
  "BDW": ["Katsina", "Bindawa"],
  "CRC": ["Katsina", "Charanchi"],
  "DDM": ["Katsina", "Dandume"],
  "DJA": ["Katsina", "Danja"],
  "DMS": ["Katsina", "Danmusa"],
  "DRA": ["Katsina", "Daura"],
  "DTS": ["Katsina", "Dutsi"],
  "DTM": ["Katsina", "Dutsinma"],
  "FSK": ["Katsina", "Faskari"],
  "FTA": ["Katsina", "Funtua"],
  "NGW": ["Katsina", "Ingawa"],
  "JBY": ["Katsina", "Jibia"],
  "KFY": ["Katsina", "Kafur"],
  "KAT": ["Katsina", "Kaita"],
  "KNK": ["Katsina", "Kankia"],
  "KKR": ["Katsina", "Kankara"],
  "KTN": ["Katsina", "Katsina"],
  "KUF": ["Katsina", "Kurfi"],
  "KSD": ["Katsina", "Kusada"],
  "MDW": ["Katsina", "Mai’adua"],
  "MLF": ["Katsina", "Malumfashi"],
  "MAN": ["Katsina", "Mani"],
  "MSH": ["Katsina", "Mashi"],
  "MTZ": ["Katsina", "Matazu"],
  "MSW": ["Katsina", "Musawa"],
  "RMY": ["Katsina", "Rimi"],
  "SBA": ["Katsina", "Sabua"],
  "SFN": ["Katsina", "Safana"],
  "SDM": ["Katsina", "Sandamu"],
  "ZNG": ["Katsina", "Zango"],
  "TGD": ["Cross River", "Abi (Itigidi)"],
  "KAM": ["Cross River", "Akamkpa"],
  "KTA": ["Cross River", "Akpabuyo (Headquarters at Ikot Nakanda)"],
  "BKS": ["Cross River", "Bakassi"],
  "ABE": ["Cross River", "Bekwarra (Headquarters at Abuochicie)"],
  "AKP": ["Cross River", "Biase (Headquarters at Akpet-Central)"],
  "BJE": ["Cross River", "Boki (Boje)"],
  "CAL": ["Cross River", "Calabar Municipal"],
  "ANA": ["Cross River", "Calabar south (Anantigha)"],
  "EFE": ["Cross River", "Etung (Effraya)"],
  "KMM": ["Cross River", "Ikom"],
  "BNS": ["Cross River", "Obanliku (Sankwala)"],
  "BRA": ["Cross River", "Obubra"],
  "UDU": ["Cross River", "Obudu"],
  "DUK": ["Cross River", "Odukpani"],
  "GGJ": ["Cross River", "Ogoja"],
  "GEP": ["Cross River", "Yakurr"],
  "CKK": ["Cross River", "Yala (Okpoma)"],
  "KGK": ["Kaduna", "Kagarko"],
  "KCH": ["Kaduna", "Kachia"],
  "KJR": ["Kaduna", "Kajuru"],
  "KJM": ["Kaduna", "Chikun (Kujama)"],
  "KWB": ["Kaduna", "Jaba (Kwoi)"],
  "KAF": ["Kaduna", "Jema'a (Kafanchan)"],
  "KRU": ["Kaduna", "Kauru"],
  "KRA": ["Kaduna", "Kaura"],
  "KAR": ["Kaduna", "Ikara"],
  "MKR": ["Kaduna", "Makarfi"],
  "MKA": ["Kaduna", "Kaduna South (Makera)"],
  "DKA": ["Kaduna", "Kaduna North (Doka)"],
  "GKW": ["Kaduna", "Giwa"],
  "HKY": ["Kaduna", "Kudan (Hunkuyi)"],
  "ZKW": ["Kaduna", "Zangon Kataf (Zonkwa)"],
  "TRK": ["Kaduna", "Igabi (Turunku)"],
  "SNK": ["Kaduna", "Lere (Saminaka)"],
  "ANC": ["Kaduna", "Kubau (Anchau)"],
  "MGN": ["Kaduna", "Soba (Maigana)"],
  "BNG": ["Kaduna", "Birnin Gwari"],
  "SBG": ["Kaduna", "Sabon Gari (Sabon Garin Zaria)"],
  "ZAR": ["Kaduna", "Zaria"],
  "GWT": ["Kaduna", "Sanga (Gwanto)"],
  "FGE": ["Kano", "Fagge"],
  "DAL": ["Kano", "Dala"],
  "TRN": ["Kano", "Tarauni"],
  "NSR": ["Kano", "Nasarawa"],
  "GWL": ["Kano", "Gwale"],
  "UGG": ["Kano", "Ungogo"],
  "KBT": ["Kano", "Kumbotso"],
  "DTF": ["Kano", "Dawakin Tofa"],
  "KMC": ["Kano", "Kano Municipal"],
};
